apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zookeeper
  namespace: zookeeper
spec:
  interval: 30m
  chart:
    spec:
      chart: zookeeper
      version: "12.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    replicaCount: 3
    image:
      registry: public.ecr.aws
      repository: bitnami/zookeeper
      tag: 3.9.2
    persistence:
      enabled: true
      storageClass: ebs-gp2
      size: 8Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - zookeeper
            topologyKey: kubernetes.io/hostname
    service:
      type: ClusterIP
    heapSize: 256
    metrics:
      enabled: false
