---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-credentials
  namespace: clickhouse
spec:
  encryptedData:
    admin-password: AgAIj6bsZUirHT/RoFtJX8FmJVH6m669TW50Ut2bmEjrXFJPw4az/wQqvuasTb2rm3bE7Pl0nKbicdT+QUYU6E34O6C4s6vfqbel4PKcb7tqq4ExzVkFP6zhZYObEqIqiZBju+CsltqWzJGMdjjlNpjZlztaDZNBZ4XT3pJhsS4eSwmT9dxEA7czJqX4eK0hpByTYh/SwQmWahGUHdeF864/1NTgRheHUQ5mQXhRr9+W3mprsulc1H0uyIQ4GObnn1BNY67v2ZQGUjEeX21wglIpMtAVs50SuJIFKkQMvHS83R1cH0HKmgPOgTDSxB/ItX5ktm6CiFN8zHJz3qFKn+fyQofx5M/qLv/sAprvwMaWBK3W/4SO5b1NOzQj398nE3lm2v+ui0vxkpe+O3vTOUNqf60kZKqJyCEjP6tXeKL2K4GoRhJRN/4c2inQBJB9shYH458VxqkqcDfmfaX9YA0Rr2fkejcl0VX2tuTzAxrnNUCYQgF3lzXSU9Pm+TfakbNuIbOArdbJJcUr+4e+thir63s0CIea+UzdEz5/evaGPzz+LOYy07RZKUMJjwyuvXLQwICsN8mG1Kr7BvnCxOxjE/+pSrz0DmxJcF1qTe11iMHvAJoZy22KPnzgLFOwyVhN25vLKBnAzZspLPMxOSA0h5v9w2TefTT7YmC7+2fsuvWOeEIom/1NDTVhZhx97iIpk06ahV8+ku6pIFJZ
  template:
    metadata:
      name: clickhouse-credentials
      namespace: clickhouse
